server:
  port: 5001

spring:
  application:
    name: user-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

auth:
  verification-token-ttl-hours: ${VERIFICATION_TOKEN_TTL_HOURS}
  refresh-token-ttl-days: ${REFRESH_TOKEN_TTL_DAYS}
  max-failed-login-attempts: ${MAX_FAILED_LOGIN_ATTEMPTS}
  account-lockout-minutes: ${ACCOUNT_LOCKOUT_MINUTES}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-ttl-minutes: ${ACCESS_TOKEN_TTL_MINUTES}


