server:
  port: 5003

spring:
  application:
    name: airline-core-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

airline:
  owner-role-id: ${AIRLINE_OWNER_ROLE_ID}



