CREATE TABLE IF NOT EXISTS airline_onboarding_applications (
    id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    applicant_user_id      BIGINT NOT NULL,
    initial_admin_user_id  BIGINT,
    legal_name             VARCHAR(255) NOT NULL,
    display_name           VARCHAR(255) NOT NULL,
    iata_code              VARCHAR(2),
    icao_code              VARCHAR(3),
    country                VARCHAR(255) NOT NULL,
    registration_number    VARCHAR(100) NOT NULL,
    alliance               VARCHAR(255),
    website                VARCHAR(255),
    logo_url               VARCHAR(255),
    support_email          VARCHAR(255),
    support_phone          VARCHAR(255),
    support_hours          VARCHAR(255),
    headquarters_city_id   BIGINT,
    status                 ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN') NOT NULL DEFAULT 'DRAFT',
    rejection_reason       TEXT,
    submitted_at           DATETIME(6),
    reviewed_at            DATETIME(6),
    created_at             DATETIME(6) NOT NULL,
    updated_at             DATETIME(6) NOT NULL
);
