CREATE TABLE IF NOT EXISTS onboarding_documents (
    id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    application_id         BIGINT NOT NULL,
    document_type          ENUM('CERTIFICATE_OF_INCORPORATION', 'AIR_OPERATOR_CERTIFICATE', 'OPERATING_LICENSE',
                                'BUSINESS_REGISTRATION', 'OTHER') NOT NULL,
    original_file_name     VARCHAR(255) NOT NULL,
    declared_content_type  VARCHAR(150),
    storage_provider       VARCHAR(50) NOT NULL,
    storage_bucket         VARCHAR(255) NOT NULL,
    storage_key            VARCHAR(500) NOT NULL,
    detected_content_type  VARCHAR(150),
    file_size              BIGINT,
    checksum_sha256        VARCHAR(64),
    status                 ENUM('PROCESSING', 'CLEAN', 'BLOCKED', 'VERIFIED', 'REJECTED') NOT NULL DEFAULT 'PROCESSING',
    blocked_reason         VARCHAR(500),
    processing_attempts    INT NOT NULL DEFAULT 0,
    uploaded_by_user_id    BIGINT NOT NULL,
    verified_by_user_id    BIGINT,
    verified_at            DATETIME(6),
    rejection_reason       TEXT,
    created_at             DATETIME(6) NOT NULL,
    updated_at             DATETIME(6) NOT NULL,
    CONSTRAINT uk_onboarding_documents_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_onboarding_documents_application FOREIGN KEY (application_id) REFERENCES airline_onboarding_applications (id),
    INDEX idx_onboarding_documents_application_type (application_id, document_type),
    INDEX idx_onboarding_documents_status_updated (status, updated_at)
);
