package com.sunday.common_lib.enums;

public enum ReviewDecision {
    APPROVED,
    REJECTED,
    REQUESTED_CHANGES,
    OWNER_ASSIGNED,
    PROVISIONED,
    COMMENTED,
    INFORMATION_REQUESTED,
    INFORMATION_PROVIDED,
    STAGE_ASSIGNED,
    STAGE_APPROVED,
    STAGE_REJECTED,
    REFERRED,
    SENT_BACK,
    WITHDRAWN,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED
}
